### ISSUE TITLE
Empty strings labelling error

### ISSUE THREAD

**Issue by alastairrushworth** [wilkox/ggfittext#10]
Hi @wilkox , thanks again for the awesome package!

I noticed (via an [inspectdf issue](https://github.com/alastairrushworth/inspectdf/issues/12)) that `ggfittext::geom_fit_text()` returns an error when any of the labels are 0 length strings (example below).  I can add a fix for this locally for `inspectdf` (maybe replacing empties with something generic to display - I'm not sure yet, though if you have an opinion on this I'd also be keen to hear).  For `ggfittext` specifically, I wondered more generally if the error should be made more meaningful, or whether the `geom_fit_text()` can be adapted to handle empties.

Thanks!  

Alastair

```
library(ggplot2)
presidential$name[1] <- ""
ggplot(presidential, 
       aes(ymin = start, ymax = end, label = name, x = party)) +
  geom_fit_text(grow = TRUE)
```

**Comment by wilkox** [comment]
Thanks for reporting this @alastairrushworth, this is definitely not ideal behaviour! Fixed in 669c58a, and I've submitted it to CRAN as version 0.8.1 so you shouldn't have to update `inspectdf` to work around it.
