### ISSUE TITLE
Warning message: Stacking not well defined when not anchored on the axis 

### ISSUE THREAD

**Issue by alastairrushworth** [wilkox/ggfittext#13]
Hi again  @wilkox - thanks for your support this week.  I think this question will probably be the last one from me for while 😊.  I think I owe you a beer.

I have a case (also in `inspectdf`) where I build a stacked bar chart using `geom_bar()` then add labels with `geom_fit_text()`

```
library(ggfittext)
library(ggplot2)
library(magrittr)

x = data.frame(x = rep("a", 2), y = c(2, 2), lb = c(1, 2))
x %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", colour = "black") + 
  geom_fit_text(position = "stack")
```
When printed, a warning is emitted: `Warning message: Stacking not well defined when not anchored on the axis`.  This seems to be a `ggplot2` message `https://github.com/tidyverse/ggplot2/blob/master/R/position-stack.r` that has something to do with the range of the data having to include 0.  

I'd like to be able to hide the warning from users if possible - as far as I can tell, the warning isn't required as `ggfittext` is working perfectly in this case.  Do you think there is a way around this?

**Comment by wilkox** [comment]
Hi Alastair,

Keep the issues coming if you have them! You're helping me to find a lot of the rough edges in the package 😃

There are a couple of options here. One is to set `ymin` and `ymax` explicitly; ggplot2 is happy to stack boxes defined this way:

``` r
library(ggfittext)
library(ggplot2)
library(magrittr)

x = data.frame(x = rep("a", 2), y = c(2, 2), lb = c(1, 2))
x %>%
  ggplot(aes(x = x, y = y, label = lb, ymin = 0, ymax = y)) + 
  geom_bar(stat = "identity", colour = "black") + 
  geom_fit_text(position = "stack")
```

![](https://i.imgur.com/72WpIw6.png)

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The other would be to use `geom_bar_text()`:

``` r
library(ggfittext)
library(ggplot2)
library(magrittr)

x = data.frame(x = rep("a", 2), y = c(2, 2), lb = c(1, 2))
x %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", colour = "black") + 
  geom_bar_text(position = "stack", place = "centre")
```

![](https://i.imgur.com/I4JHPrT.png)

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alastairrushworth** [comment]
Hi @wilkox, thats awesome, the first solution worked perfectly.  Thanks again for the pointer!
