### ISSUE TITLE
Use ggfittext with coord_polar()

### ISSUE THREAD

**Issue by PMassicotte** [wilkox/ggfittext#18]
Is it possible?

``` r
library(tidyverse)
library(ggfittext)

df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))

p <- ggplot(df, aes(trt, outcome, label = outcome)) +
  geom_col() +
  geom_bar_text() 

p
```

![](https://i.imgur.com/ybjCyFA.png)

``` r

# Not working as I would have expected, labels are not showing
p + 
  coord_polar()
```

![](https://i.imgur.com/tyBJyt9.png)

<sup>Created on 2020-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wilkox** [comment]
Polar coordinates don't really work with `geom_bar_text()` yet, but you can get the same effect with `geom_fit_text()`:

``` r
library(tidyverse)
library(ggfittext)

df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))

ggplot(df, aes(x = trt, y = outcome)) +
  geom_col() +
  geom_fit_text(aes(ymin = 0, ymax = outcome, label = outcome), place = "top") +
  coord_polar()
```

![](https://i.imgur.com/SGGl8wY.png)

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
