### ISSUE TITLE
fill aesthetic produces warning even though it's needed for contrast = TRUE

### ISSUE THREAD

**Issue by zilch42** [wilkox/ggfittext#19]
Hi,

This isn't a huge issue but don't think it's needed, and is a little misleading. Including a fill aesthetic in geom_bar_text() is required when using contrast = TRUE, but produces the following warning:

```
library(tidyverse)
library(ggfittext)

mtcars %>% ggplot()+
  geom_col(aes(x=cyl, y=mpg, fill=gear))+
  geom_bar_text(aes(x = cyl, y = mpg, fill = gear), 
                size = 8, position = "stack", place = "centre", 
                min.size = 6, contrast = TRUE) 
```
```
Warning message:
Ignoring unknown aesthetics: fill 
```

There is no warning when using contrast = TRUE without a fill aesthetic, which would probably be more useful.

**Comment by wilkox** [comment]
Thanks for the bug report! I've added a fix for this in the development version.
