### ISSUE TITLE
Feature request: bar graphs

### ISSUE THREAD

**Issue by sda030** [wilkox/ggfittext#2]
Hi, nifty package. Would it be possible to implement a feature for the labels (typically percentages) that could be printed on top of a stacked bar graph? Or at least hide those which won't fit?
I am currently using 
`geom_col(position = "fill") +
 geom_text(aes(label = sprintf(prop*100, fmt="%1.0f%%")), position = position_stack(vjust = 0.5), size=3)`

![desc_impcur_topic_var_18](https://user-images.githubusercontent.com/13221371/33516906-a9cc5a1c-d77a-11e7-8b04-e34046b2811c.png)

**Comment by wilkox** [comment]
Thanks @sda030. Stacked positions is definitely on the future additions list, as soon as I can figure out how to do it properly.

**Comment by wilkox** [comment]
@sda030 I've just pushed a dev version with support for `position = "stack"`. To do this I had to change width and height from aesthetics to arguments, which is probably an improvement anyway. You'll still need to manually adjust the height/width to fit the bar. You can install the dev version with `devtools::install_github("wilkox/ggfittext").

```{r}
breakdown <- data.frame(sector = rep("fast food", 4),
                        firm = c("McDonalds", "KFC", "Hungry Jacks", "Subway"),
                        share = c(40, 20, 8, 32))
ggplot(breakdown, aes(x = sector, y = share, fill = firm, label = firm)) +
  geom_bar(position = "stack", stat = "identity") +
  geom_fit_text(position = "stack", grow = T) +
  coord_flip()
```
![screen shot 2017-12-13 at 12 22 18](https://user-images.githubusercontent.com/726198/33917087-4a4f6eec-e000-11e7-83ba-a258d5ccb4af.png)

Please give it a try and let me know how it works for you!

**Comment by sda030** [comment]
Tried out a few ways and works well! (Sorry late reply)
