### ISSUE TITLE
Numbers don't move outside a small bar when using coord_flip()

### ISSUE THREAD

**Issue by ds-jim** [wilkox/ggfittext#23]
Hello,

I've found that when using coord_flip on a bar chart the numbers don't automatically move outside the bar like they do without it.

I've used the example from the vignette on here;

```
ggplot(altitudes, aes(x = craft, y = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text() +
     coord_flip()
```

![example](https://user-images.githubusercontent.com/32925514/83361300-aef9c500-a37f-11ea-871e-c7ad00b31f38.png)

**Comment by ds-jim** [comment]
I've also found the new ggplot2 3.3.0 syntax for a bar chart on its side doesn't work

```
ggplot(altitudes, aes(y = craft, x = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text()
```

**Comment by wilkox** [comment]
Thanks a lot for this bug report! It helped me to root out several flaws in the way `geom_bar_text()` handles flipped coordinates. I've just pushed a development version with a fix and it will be on its way to CRAN soon.

``` r
library(ggplot2)
library(ggfittext)

ggplot(altitudes, aes(x = craft, y = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text() +
  coord_flip()
```

![](https://i.imgur.com/F0LnMlk.png)

``` r
ggplot(altitudes, aes(y = craft, x = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text()
```

![](https://i.imgur.com/4jd56PH.png)

<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ds-jim** [comment]
Fantastic, thank you for the update! I love to show numbers on my bar graphs and this package has streamlined my life so much.

**Comment by ds-jim** [comment]
This issues seems to have returned...

I've got the latest dev version installed (ggfittext_0.9.1.9003), `coord_flip()` seems to work fine but switching up the `x=` and `y=` is having the previous effect of the numbers not being placed correctly.

**Comment by wilkox** [comment]
Thanks for reporting this @ds-jim, it looks like the trick used to detect a horizontal `geom_col()` was not working with the current version of ggplot2. I've just pushed a fix to the development version.

``` r
library(ggplot2)
library(ggfittext)
packageVersion("ggfittext")
#> [1] '0.9.1.9004'

ggplot(altitudes, aes(y = craft, x = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text()
```

![](https://i.imgur.com/p9MoHr9.png)

<sup>Created on 2023-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
