### ISSUE TITLE
Curve text around a path

### ISSUE THREAD

**Issue by srvanderplas** [wilkox/ggfittext#24]
It would be very cool to have the ability to not just use polar transforms on text, but to curve text around an arbitrary path. I'll admit I have no idea how to do it, but I'm asking because I'm hoping to create something like the [electoral snake](https://fivethirtyeight.com/wp-content/uploads/2016/09/snake_09221.png?w=575) plot.

**Comment by wilkox** [comment]
Thanks for the suggestion! This might be a bit outside the scope of ggfittext but I'll keep it in mind as a possible future feature.

**Comment by wilkox** [comment]
This is solved by [geomtextpath](https://github.com/AllanCameron/geomtextpath), so I don't plan to add it to ggfittext.
