### ISSUE TITLE
Size as aestetic

### ISSUE THREAD

**Issue by rasmusagren** [wilkox/ggfittext#27]
Thank you so much for an excellent package! I might be missing something here, but it it possible to specify a default size and only have this kick in if the label doesn't fit? It seems like a common use case. In my situation I'm trying to plot metabolic pathways, where I would like gene and metabolite names to fit in their shapes, but I don't want very short names to be huge. If this seems like too specific a use case, I wonder if it's possible to use this to calculate and extract positions and sizes to then plot them "manually". Thanks again!

Cheers,
Rasmus

**Comment by BradyAJohnston** [comment]
Hi @rasmusagren I don't know if you've had success with this, but in poking around trying to get some other stuff working I found that you can do that without a problem. You can pass `size` as one of the `...` arguments in `geom_fit_text(size = 8)`.

The font should only increase in size if you specify `grow = TRUE`. 

### Normal
```r
ggplot(animals, aes(x = type, y = flies, label = animal)) +
  geom_tile(fill = "white", colour = "black") +
  geom_fit_text()
```
![image](https://user-images.githubusercontent.com/36021261/117241206-3770c780-ae65-11eb-926a-9c78f41aea38.png)


### Specific size
```r
ggplot(animals, aes(x = type, y = flies, label = animal)) +
  geom_tile(fill = "white", colour = "black") +
  geom_fit_text(size = 10)
```
![image](https://user-images.githubusercontent.com/36021261/117241258-53746900-ae65-11eb-8792-7edd91f12fed.png)

### Growing Smaller Text
```r
ggplot(animals, aes(x = type, y = flies, label = animal)) +
  geom_tile(fill = "white", colour = "black") +
  geom_fit_text(grow = TRUE)
```
![image](https://user-images.githubusercontent.com/36021261/117241286-61c28500-ae65-11eb-87af-cf1f18e12997.png)

**Comment by wilkox** [comment]
Thanks Brady for your response, and sorry Rasmus it's taken me so long to get to this issue! Brady's answer is correct – the default situation is for the text to have a fixed size (12 by default, but can be changed with the `size` argument) and only shrink if the box is too small. You should only get the 'huge' labels if `grow = TRUE`, or if size 12 is already very large compared to the size of your boxes. In the latter case you should probably set a smaller `size`.

If it's still not looking the way you want please post a [reprex](https://reprex.tidyverse.org) and I can try and tweak it for you.
