### ISSUE TITLE
Warning: Ignoring unknown aesthetics: label

### ISSUE THREAD

**Issue by gregleleu** [wilkox/ggfittext#29]
`geom_bar_text`  produces a warning when the label is given in the aesthetics.

```
data(iris)

library(ggplot2)
library(tidyverse)
library(ggfittext)

iris %>% 
  sample_frac(0.6) %>% 
  count(Species) %>% 
  ggplot() +
  geom_col(aes(x = Species, y = n)) +
  geom_bar_text(aes(x = Species, y = n))
```
is ok. But then

```
iris %>% 
  sample_frac(0.6) %>% 
  count(Species) %>% 
  ggplot() +
  geom_col(aes(x = Species, y = n)) +
  geom_bar_text(aes(x = Species, y = n, label = n))
```
produces the warning.

When the main ggplot code checks with parameters the geom understands, `label` does not appear in the list, hence the warning. (here https://github.com/tidyverse/ggplot2/blob/de5d63f7eba06e507187f34780bea071cb31fee4/R/layer.r#L117)
I imagine `label` needs to be added to the list here https://github.com/wilkox/ggfittext/blob/2c93955713943b902ca3e1b188d0619b0d92e206/R/geom_bar_text.R#L68 but I haven't tried it.

**Comment by wilkox** [comment]
Thanks for reporting this @gregleleu, I've pushed a fix to the development version.

**Comment by gregleleu** [comment]
Thanks,
By making it required I think you're overriding your previous behavior which was to use "y" as the label by default. OK with me, but a breaking change I think. Maybe it is supposed to be in default_aes for this not to happen.

**Comment by wilkox** [comment]
Thanks, I think you're right. Moved it to default_aes. I have a vague memory of fiddling around with this when first writing geom_bar_text() and eventually leaving label out of both required_aes and default_aes for some reason, but as far as I can tell this is not introducing any new bugs or unexpected behaviour...
