### ISSUE TITLE
Add thousands separator to geom_bar_text output

### ISSUE THREAD

**Issue by tungttnguyen** [wilkox/ggfittext#32]
Hello,

I was wondering if it's possible to add thousands separator to the label created by `geom_bar_text`. I tried to search around but couldn't find any answer to this. Thank you for any pointer!

``` r
library(ggplot2)
library(ggfittext)

ggplot(altitudes, aes(x = craft, y = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text()
```

![](https://i.imgur.com/s2ZqiNk.png)

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by BradyAJohnston** [comment]
Not directly inside of `{ggfittext}` but you can use the `{scales}` package that comes with `{ggplot2}` for format the label before passing it to label, as below.

```r
library(ggplot2)
library(ggfittext)

altitudes$label <- scales::comma(altitudes$altitude)

ggplot(altitudes, aes(x = craft, y = altitude, label = label)) +
  geom_col() +
  geom_bar_text()
```
![image](https://user-images.githubusercontent.com/36021261/162552836-2a8c444a-eeb2-42d0-9d13-fd234ca9d39e.png)

**Comment by tungttnguyen** [comment]
Thank you!

**Comment by wilkox** [comment]
Thanks @BradyAJohnston. I would also point out that `geom_bar_text()` and `geom_fit_text()` both take a `formatter` argument, which lets you specify a function to be applied to the text before it is drawn:

``` r
library(ggplot2)
library(ggfittext)

ggplot(altitudes, aes(x = craft, y = altitude, label = altitude)) +
  geom_col() +
  geom_bar_text(formatter = scales::comma)
```

![](https://i.imgur.com/Wu4Yeit.png)

<sup>Created on 2022-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
