### ISSUE TITLE
Constraining within a polygon, not just a geom_rect() or geom_tile()?

### ISSUE THREAD

**Issue by rossdrucker** [wilkox/ggfittext#34]
Asking more as a general inquiry, but is it possible to specify a custom boundary to constraining the text size? For example, if I had a trapezoid or a diamond or a triangle that I'd defined as a bounding coordinate, is there a way to use `geom_fit_text()` and have the text fully fill the bounding polygon? I can elaborate more as needed, but ideally, something like the following would work:

```
library(ggplot2)
library(ggfittext)

# Create a boundary for the text
text_boundary_df <- data.frame(
  x = c(0.75, 0.25, -0.75, -0.25, 0.75),
  y = c(0.25, 0.75, -0.25, -0.75, 0.25),
  text_to_fit = "A"
)

# Create a ggplot object with no data frame passed to it (per my use case)
g <- ggplot()

# Add some data to plot with geom_polygon()
g <- g +
  geom_polygon(
    data = df,
    aes(
      x = x,
      y = y,
      ....
    )
  )

# Add the constrained text
g <- g + 
  geom_polygon(
    data = text_boundary_df,
      aes(
        x = x,
        y = y
      ) 
  ) +
  geom_fit_text(
    data = text_boundary_df,
    aes(
      x = x,
      y = y,
      label = text_to_fit
    ) ,
    grow = TRUE
  )
```

Ideally this would place the "A" text inside of a rotated rectangle; is something like this possible?

**Comment by wilkox** [comment]
At the moment ggfittext can't do this, and it would be difficult to extend `geom_fit_text()` to do this as it would require fundamental changes to the algorithm. I can conceive of something like a `geom_poly_text()` for reflowing text to a polygon, although at the moment I can't think of an efficient way to shrink/grow the text if it doesn't fit well.

Out of curiosity, what is the use case for this?

**Comment by rossdrucker** [comment]
I author and maintain [sportyR](https://www.github.com/sportsdataverse/sportyR), a package to create scaled versions of sports playing surfaces as defined by league rule books. In the NFL and NCAA Football rule books, the dimensions of the yardage-marking numbers are defined.

I can use these dimensions to define a bounding box for the numbers, and when no rotation is applied to the field (a feature of `sportyR` is the ability to rotate plots as desired) I can use `geom_fit_text()` to obey these dimensions and have the numbers plot correctly. However, when there's a rotation applied, `sportyR` will appropriately rotate all of the features on the surface, and the numbers should be rotated as well.

I have the rotational logic working with `geom_text()`, but this doesn't allow me to use the bounding box's dimensions to define the font size, and `geom_rect()` and `geom_tile()` don’t rotate.

What I was hoping was that I could define the bounding box of an unrotated rectangle, use `ggfittext`'s ability to appropriately size the text, and then finally rotate both the `(x, y)` coordinates of the numbers on the plot as well as the appropriate rotation of the text. Or, to rotate the bounding box (a normal rectangle to a rotated rectangle/a polygon) and then fit the text within its boundaries.

Hope that helps and makes sense... happy to clarify further.

**Comment by wilkox** [comment]
If I'm understanding correctly, I think it should be possible to rotate the bounding box for the yardage mark, then generate a new bounding box for the text using the maximum extent of the rotated yardage mark box in (x, y). Then fit the text, rotated with 'angle' to match the rotation of the playing surface, to the new bounding box:

``` r
library(tidyverse)
library(ggfittext)

# Coordinates of rotated yardage mark
rym <- data.frame(x = c(1, 3, 7, 5), y = c(3, 1, 5, 7))

# Coordinates of the bounding box for text drawn in the RYM, derived from the RYM coordinates
bb <- data.frame(xmin = min(rym$x), xmax = max(rym$x), ymin = min(rym$y), ymax = max(rym$y))
bb_poly <- data.frame(
  x = c(bb$xmin, bb$xmax, bb$xmax, bb$xmin),
  y = c(bb$ymin, bb$ymin, bb$ymax, bb$ymax)
)

ggplot() +
  # Blue rectangle is the rotated yardage mark
  geom_polygon(data = rym, aes(x = x, y = y), fill = "blue", alpha = 0.5) +
  # Red rectangle is the bounding box derived from the rotated yardage mark
  geom_polygon(data = bb_poly, aes(x = x, y = y), fill = "red", alpha = 0.5) +
  # Text is drawn in the bounding box with the appropriate rotation applied
  geom_fit_text(
    data = bb,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
    label = "123",
    grow = TRUE,
    angle = 45
  ) +
  coord_fixed()
```

![](https://i.imgur.com/jnn6pWq.png)

<sup>Created on 2022-08-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rossdrucker** [comment]
That's **exactly** what I was hoping to do! Based on the documentation, I thought I needed to supply `geom_rect()` or `geom_tile()` first. Thank you!
