### ISSUE TITLE
allow numeric assignments to 'width' and 'height' params

### ISSUE THREAD

**Issue by corybrunson** [wilkox/ggfittext#4]
Hi! This package is just what i was hoping to find, having run into plenty of issues squeezing text into boxes in a **ggplot2** extension of my own.

I admittedly don't understand the constraints governing #2 , but it does seem consistent with other geoms (e.g. `ggplot2::geom_tile()`) to leave `width` and `height` as parameters rather than aesthetics. However, in other geoms (in my experience) this is done by passing numeric values (taken to be on the axis scales) rather than units. It seems worthwhile to allow both numeric and unit assignments, depending on the user's needs. In [the params branch on my fork](https://github.com/corybrunson/ggfittext/tree/params), i added `setup_params` and `setup_data` to `GeomFitText` and rearranged some of the internals in order to achieve this. I don't know if it upsets any existing uses, but it doesn't seem to cause problems for the vignette or **testthat** examples. (I added  some tests, too.)

I should stress that i'm not a **ggplot2** expert and my fixes derive from my own largely trial-and-error experience. That said, if this seems reasonable to you, i can send a PR, and either way i'd be very glad to have this functionality in a future release. Thanks for the great tool!

**Comment by wilkox** [comment]
Thanks for the contribution @corybrunson! I'm still unsure about the best way to manage discrete axes but this seems like a step in the right direction. Could you submit this as a PR?

**Comment by corybrunson** [comment]
Done!
