### ISSUE TITLE
Feature Request: Diverging bar plots

### ISSUE THREAD

**Issue by moldach** [wilkox/ggfittext#6]
I'm having an issue trying to use `geom_fit_text()` on diverging bar graphs. It would be nice if `geom_fit_text()` worked better for the following:
```
library(ggplot2)
library(ggfittext)
theme_set(theme_bw())  

# Data Prep
data("mtcars")  # load data
mtcars$`car name` <- rownames(mtcars)  # create new column for car names
mtcars$mpg_z <- round((mtcars$mpg - mean(mtcars$mpg))/sd(mtcars$mpg), 2)  # compute normalized mpg
mtcars$mpg_type <- ifelse(mtcars$mpg_z < 0, "below", "above")  # above / below avg flag
mtcars <- mtcars[order(mtcars$mpg_z), ]  # sort
mtcars$`car name` <- factor(mtcars$`car name`, levels = mtcars$`car name`)  # convert to factor to retain sorted order in plot.

# Diverging Barcharts
ggplot(mtcars, aes(x=`car name`, y=mpg_z, label=mpg_z)) + 
  geom_bar(stat='identity', aes(fill=mpg_type), width=.5)  +
  geom_fit_text(aes(label = mpg_z)) +
  scale_fill_manual(name="Mileage", 
                    labels = c("Above Average", "Below Average"), 
                    values = c("above"="#00ba38", "below"="#f8766d")) + 
  labs(subtitle="Normalised mileage from 'mtcars'", 
       title= "Diverging Bars") + 
  coord_flip()
```
![normal](https://user-images.githubusercontent.com/5749465/41557804-003735f8-72fc-11e8-92cd-65dbb2dd69b9.png)

If I try the `grow = T` option I get:

![grow](https://user-images.githubusercontent.com/5749465/41557814-09b6fcd0-72fc-11e8-96ae-401a32133973.png)

And if I use the`position = "stack"` option i get:

![stack](https://user-images.githubusercontent.com/5749465/41557830-1f75b548-72fc-11e8-8109-086dbf52c854.png)

It looks like the `position ="stack"` option is the closest to what I am desiring. Are "Dodge Challenger" and the others not mapped because they are simply too big of strings too fit inside the bars?

**Comment by wilkox** [comment]
Hi @moldach,

The main reason your example doesn't work well is that it doesn't give `geom_fit_text` a defined box in which to draw the text. This is usually done with either `xmin`/`xmax` or `x`/`width`, plus either `ymin`/`ymax` or `y`/`height`.

It's possible to achieve what you want with the current version:

``` r
# Libraries
library(ggplot2)
library(ggfittext)

# Calculate normalised mpg
mtcars$mpg_z <- round((mtcars$mpg - mean(mtcars$mpg)) / sd(mtcars$mpg), 2)
mtcars$mpg_type <- ifelse(mtcars$mpg_z > 0, "Above average", "Below average")

# Convert car name from rowname to column
mtcars$car <- rownames(mtcars)

# Sort by normalised mpg
mtcars <- mtcars[order(mtcars$mpg_z), ]
mtcars$car <- factor(mtcars$car, levels = mtcars$car)

# Draw diverging bar chart
ggplot(mtcars, aes(x = car, y = mpg_z, fill = mpg_type)) + 
  geom_col(width = .5)  +
  geom_fit_text(
    data = subset(mtcars, mpg_z > 0),
    aes(x = car, ymin = 0, ymax = mpg_z, label = car),
    height = grid::unit(2, "mm"),
    min.size = 0,
    inherit.aes = FALSE,
    place = "right"
  ) +
  geom_fit_text(
    data = subset(mtcars, mpg_z < 0),
    aes(x = car, ymin = mpg_z, ymax = 0, label = car),
    height = grid::unit(2, "mm"),
    min.size = 0,
    inherit.aes = FALSE,
    place = "left"
  ) +
  scale_fill_manual(name = "Mileage", values = c("#00ba38", "#f8766d")) + 
  labs(subtitle = "Normalised mileage from 'mtcars'", 
       title = "Diverging Bars") + 
  coord_flip() +
  theme_bw()
```

![](https://i.imgur.com/hNsJz0y.png)

It's not obvious to me that `ggfittext` is necessarily the best tool for this task though – you could achieve a very similar result with just `geom_text` and a fixed font size.
