### ISSUE TITLE
vjust doesn't appear to be doing anything.

### ISSUE THREAD

**Issue by wdm0336** [wilkox/ggfittext#7]
Trying to get vjust to work. 0 should  put it at the bottom of the bar (as per docs) but doesn't appoear to me to have any affect:

`ggplot(coffees, aes(x = coffee, y = proportion, label = ingredient,
                    fill = ingredient)) +
  geom_col(position = "dodge") +
  geom_bar_text(position = "dodge", grow = TRUE, reflow = TRUE, vjust = 0)`

Would really like to be able to put it above each bar of the bar plot with a vjust, but I don't think that is supported. Tried -0.3 (as I would do to move the text above the bar without this package) and that doesn't work either.

Using R3.6 and v0.8.0 of ggfittext.

**Comment by wilkox** [comment]
`vjust` and `hjust` don't work quite the same way in ggfittext as they do in ggplot2. In ggplot2 they control both the alignment of the text and the text position. In ggfittext they control alignment only, with position controlled by `place`.

For what you're trying to achieve, `geom_fit_text()` is probably more appropriate:

``` r
library(ggplot2)
library(ggfittext)

ggplot(coffees, aes(x = coffee, y = proportion, label = ingredient, fill = ingredient)) + 
  geom_col(position = "dodge") + 
  geom_fit_text(aes(ymin = proportion, ymax = 1), position = "dodge", place = "bottom", grow = TRUE, reflow = TRUE)
```

![](https://i.imgur.com/ramUDp1.png)

<sup>Created on 2019-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
