### ISSUE TITLE
Consider adding ggfittex to ggplot2-exts

### ISSUE THREAD

**Issue by Rekyt** [wilkox/ggfittext#9]
👋 Hi @wilkox,
Have you considered adding `ggfittext` to the [ggplot2 extensions gallery](https://github.com/ggplot2-exts/gallery). It is a searchable repository with an [associated website](http://www.ggplot2-exts.org/gallery/) that contains a list of ggplot2 extensions.

You can add `ggfittext` to the repository by making a PR in the `ggplot2-exts` repository.

**Comment by wilkox** [comment]
Thanks for the great suggestion @Rekyt! I've submitted a PR.
